org: dcaldwell
app: groupme-music-bot
service: groupme-music-bot

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
plugins:
  - serverless-offline

functions:
  api:
    handler: handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: groupme-callback
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY
